name: Daily Scraper

on:
  schedule:
    - cron: '0 16,22 * * *'  # 12 PM and 6 PM Eastern Time (in UTC)
  workflow_dispatch:          # Manual run option

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: 'DK - Copy'
        run: |
          pip install -r requirements.txt

      - name: Run scraper script
        working-directory: 'DK - Copy'
        run: python Locks.py

      - name: Commit & push updated data
        working-directory: 'DK - Copy'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🔁 Auto-update by GitHub Action" || echo "No changes to commit"
          git push
